### ISSUE TITLE
CSS fix for vertical layout long titles

### ISSUE THREAD

**Issue by davidspring** [Jefferson49/Joomla_module_ext_menu_reloaded#1]
Thank you for updating this terrific extension! There is one problem which is easily fixed. On the vertical layout, menu items with long titles that take up two lines have line-height set for 1 by default. This is hard to read. As a quick fix, one can add this to the end of your template custom CSS file: 
.ux-menu.ux-menu-vertical a {line-height: 1.2 !important;}
Alternately, you can add this CSS to the end of: 
install/mod_ariextmenu/js/css/menu.min.css
However, a better solution would be to add Line Height and padding to the list of options – at least for the vertical layout – which would allow users to easily set the line height and padding to whatever works best for their website.

**Comment by Jefferson49** [comment]
Hello David,

thank you very much for your positive feedback. I also very much appreciate your review on JED!

I have already worked on your proposals to add line-height and padding to the configuration; also for the sub-menus. It was not so difficult and works very fine in my own Joomla installation.

I attached a test version of the module with the additional configuration. If you have some time, I would be happy if you could test it and provide some feedback. If it works, I will publish it as a new release soon.

[mod_ariextmenu_v5.0.0aa8b789f.zip](https://github.com/Jefferson49/Joomla_module_ext_menu_reloaded/files/13798295/mod_ariextmenu_v5.0.0aa8b789f.zip)

**Comment by davidspring** [comment]
Thanks for adding line-height and padding to the configuration. I have tested your revision on J4.4.1 with PHP 8.1 and it works very well. I will be testing it on J5 and PHP 8.2 in the near future. I will let you know if I find any problems.
For the past 16 years, I have written books and website tutorials about Joomla that have been read by more than one million people.. I also teach courses and do videos about Joomla. I will be adding your  menu extension to all of these websites, books, videos and courses during the next year. Your extension meets a very important need. I am certain it will eventually rise to the top of the JED menu system category. 
I will let you know when I post a YouTube video about your menu extension. Let me know if there is anything I can do to help. You can reach me directly via davidspring at protonmail dot com. 
Regards,
David Spring

**Comment by Jefferson49** [comment]
Thank you for testing and the positive feedback. 

I will publish the changes in a new release.

**Comment by Jefferson49** [comment]
Completed with e551cd4
